services:
  postgres_students:
    container_name: postgres_students
    image: postgres
    restart: always
    ports:
      - 6022:5432
    env_file:
      - ./back-end/.env
    volumes: 
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  node_app:
    container_name: node_app
    image: node_app_image
    build: ./back-end
    ports:
      - 4442:5000
    depends_on:
      postgres_students:
        condition: service_healthy
    links:
      - postgres_students
    env_file:
      - ./back-end/.env

  react_app:
    container_name: react_app
    build: ./front-end
    image: react_app_image
    volumes:
      - build_react:/var/www/html

  nginx_server:
    container_name: nginx_server
    build: ./nginx
    image: nginx_server_image
    ports:
      - 3007:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - postgres_students
      - node_app
      - react_app
volumes:
  db:
  build_react: