name: Deploy Amazon
on:
  push:
    branches:
      - main
jobs:
  aws_build:
    runs-on: self-hosted
      timeout-minutes: 20
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
        - name: Create Back-End .env_file
          uses: SpicyPizza/create-envfile@v1
          with:
            envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
            envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
            envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
            envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
            envkey_PORT: ${{ secrets.PORT }}
            directory: back-end/
            file_name: .env
            fails_on_empty: true
        - name: Create Front-End .env_file
          uses: SpicyPizza/create-envfile@v1
          with:
            envkey_REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
            directory: front-end/
            file_name: .env
            fails_on_empty: true
        - name: Docker Build
          run: docker-compose -f docker-compose-prod.yml build
        - name: Run App on Docker
          run: docker-compose -f docker-compose-prod.yml down && docker-compose -f docker-compose-prod.yml up -d